# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
  - build

pool:
  vmImage: node:latest

jobs:
- job: build
  steps:
    - script:
      - npm install
      - npm install -g gatsby-cli