# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-22.04'

stages:
- stage: Build
  jobs:
  - job: build_gatsby
    steps:
    - script: |
        - sudo apt-get update
        - sudo apt-get install git
        - git config --global user.name "jbos"
        - git config --global user.email "j.bos@perrit.nl"
        - sudo apt-get install curl
        - bash curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh
        - nvm install 19
        - nvm use 19
        - call npm install
        - call npm install -g gatsby-cli